# -*- coding: utf-8 -*-
{
    'name': 'Teams',
    'version': '1.0',
    'category': 'Academica',
    'description': 'Control de equipos',
    'author': 'Yo',
    'maintainer': 'Yo',
    'website': 'http://www.itsa.edu.mx',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/plays_report_template.xml',
        'views/teams_view.xml',
        'views/players_view.xml',
        'views/ligas_view.xml',
        'views/estadios_view.xml',
        'views/arbitros_view.xml',
        'views/plays_view.xml',
        'views/cedulas_view.xml',
        'views/menu_view.xml',    
    ],
    'installable': True,
    'auto_install': False,
}